# Generated by Django 4.0.3 on 2022-03-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avatar',
        ),
        migrations.AddField(
            model_name='image',
            name='avatar',
            field=models.BooleanField(default=False),
        ),
    ]
