# Generated by Django 3.2.12 on 2022-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
