# Generated by Django 3.2.12 on 2022-03-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
