# Generated by Django 3.2.12 on 2022-03-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0005_image_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='token',
        ),
    ]
