# Generated by Django 4.0.3 on 2022-04-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0006_image_banned_alter_moderationrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.comments'),
        ),
    ]
