# Generated by Django 4.0.3 on 2022-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0007_alter_complaints_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
