# Generated by Django 3.2.12 on 2022-03-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0010_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='published_date',
            new_name='date_last_own',
        ),
    ]
