# Generated by Django 3.2.12 on 2022-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0012_auto_20220305_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='secret',
            field=models.CharField(max_length=256),
        ),
    ]
